server:
  port: 8763
spring:
  application:
    name: nacos-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.104:8848
    gateway:
      discovery:
        locator:
          enabled: true

#自定义网关过滤工厂开关  enabled[开启], [其他就是关闭]
customerGatewayFilter: unabled

#路由监控(还没搞清怎么用)
management:
  endpoint:
    beans:
      enabled: true
    mappings:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, mappings, beans