server:
  port: 8763
spring:
  application:
    name: nacos-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.104:8848
    gateway:
      discovery:
        locator:
          enabled: true
      #在配置文件中设置某个服务的路由信息以及网关熔断器
      routes:
        - id: anotherCustomer
          uri: lb://nacos-customer
          predicates:
            - Method=GET
          #网关设置微服务熔断器
          filters:
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallbackcontroller

#熔断器超时设置
hystrix:
  command:
    fallbackcmd:
      execution:
        timeout:
          enable: true
        isolation:
          thread:
            timeoutInMilliseconds: 2000

#自定义网关过滤工厂开关  enabled[开启], [其他就是关闭]
customerGatewayFilter: unabled

#路由监控(还没搞清怎么用)
management:
  endpoint:
    beans:
      enabled: true
    mappings:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, mappings, beans